# Generated by Django 2.0.7 on 2020-06-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='ans',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='questions',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
