# Generated by Django 2.0.7 on 2020-06-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20200612_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
