# Generated by Django 3.0.7 on 2020-06-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20200612_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
