# Generated by Django 3.0.7 on 2020-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20200613_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='image',
            new_name='ques_img_blank',
        ),
        migrations.AddField(
            model_name='questions',
            name='ans_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_a_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_b_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_c_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_d_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='ques_img',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='media/'),
        ),
    ]
