# Generated by Django 3.0.7 on 2020-06-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20200613_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='ans_img',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_a_img',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_b_img',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_c_img',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_d_img',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='ques_img',
        ),
    ]
